#!/usr/bin/env python3
"""PDF text extraction tool - used for full text re-screening of documents

Usage:
    python extract_pdf.py <input PDF file> [--output <output file>]
    
Example:
    python extract_pdf.py paper.pdf
    python extract_pdf.py paper.pdf --output extracted.txt"""

import PyPDF2
import sys
import argparse
from pathlib import Path


def extract_text_from_pdf(pdf_path: str, output_file: str = None):
    """Extract text from PDF files and save.
    
    Args:
        pdf_path: PDF file path
        output_file: output text file path (optional, automatically generated by default)
    
    Returns:
        Output file path"""
    pdf_path = Path(pdf_path)
    
    if not pdf_path.exists():
        raise FileNotFoundError(f"not foundPDFdocument: {pdf_path}")
    
    if not pdf_path.suffix.lower() == '.pdf':
        raise ValueError(f"The file must bePDFFormat: {pdf_path}")
    
    # Automatically generate output file names
    if output_file is None:
        output_file = pdf_path.stem + '_fulltext.txt'
    
    print(f"Opening: {pdf_path}")
    
    reader = PyPDF2.PdfReader(str(pdf_path))
    num_pages = len(reader.pages)
    print(f"Total pages: {num_pages}")
    
    all_text = []
    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        if text:
            all_text.append(f'--- Page {i+1} ---\n{text}')
        else:
            all_text.append(f'--- Page {i+1} ---\n[Unable to extract text]')
        print(f'Extracted {i+1}/{num_pages} Page')
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n\n'.join(all_text))
    
    print(f'English: {output_file}')
    return output_file


def main():
    parser = argparse.ArgumentParser(
        description='Extract text from PDF files for full-text review of literature',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Example:
  python extract_pdf.py paper.pdf
  python extract_pdf.py paper.pdf --output result.txt"""
    )
    
    parser.add_argument('pdf_file', help='Input PDF file path')
    parser.add_argument('-o', '--output', help='Output text file path (optional)')
    
    args = parser.parse_args()
    
    try:
        extract_text_from_pdf(args.pdf_file, args.output)
    except FileNotFoundError as e:
        print(f"mistake: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"mistake: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Failed to extract: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
