import asyncio

import pytest
from sqlmodel import Session

from app.config import settings
from app.db import engine
from app.mcp_server import (
    _normalize_evidence_extraction_payload,
    calculate_study_sample_size, create_study_design_project, create_review_project,
    deduplicate_project_citations, export_study_design_bundle, generate_rct_randomization_schedule,
    finalize_study_design, generate_study_design_blueprint, generate_project_search_strategy, get_study_design_approval_status,
    fetch_and_save_open_access_full_text, import_citations_file_to_project, import_citations_to_project, mcp, request_study_design_approval, save_project_search_strategy, save_rct_randomization_plan,
    get_literature_access_status, save_study_design_content, search_pubmed, submit_screening_decisions,
)
from app.services.study_design import approve_study_design_record, get_study_design_workflow_events
from app.services.exporters import build_review_bundle_data


def test_mcp_workflow_tools_are_registered():
    tool_names = sorted(mcp._tool_manager._tools.keys())
    for name in ["create_review_project", "generate_project_search_strategy", "save_project_search_strategy", "get_literature_access_status", "create_research_case", "link_research_case", "get_research_case", "get_agent_project_context", "import_citations_to_project", "import_citations_file_to_project", "list_offline_evidence_packages", "import_offline_evidence_package", "ingest_offline_package_full_text", "deduplicate_project_citations", "get_formal_retrieval_status", "list_pending_screening_citation_batch", "submit_screening_decisions", "create_study_design_project", "generate_study_design_blueprint", "calculate_study_sample_size", "save_rct_randomization_plan", "request_study_design_approval", "approve_study_design", "finalize_study_design", "get_study_design_approval_status", "generate_rct_randomization_schedule", "export_study_design_bundle"]:
        assert name in tool_names
    for name in [
        "start_evidence_extraction_workflow",
        "save_evidence_extractions",
        "check_project_retractions",
        "export_evidence_table",
        "save_full_text_documents",
        "fetch_and_save_open_access_full_text",
        "save_full_text_evidence_details",
        "save_bias_assessments",
        "run_binary_meta_analysis",
        "request_systematic_evidence_review",
        "approve_systematic_evidence",
        "get_systematic_evidence_review_status",
        "export_systematic_evidence_bundle",
        "start_research_writing_workflow",
        "get_research_writing_source",
        "save_research_writing_draft",
        "request_research_writing_approval",
        "approve_research_writing",
        "get_research_writing_approval_status",
        "export_research_writing_bundle",
    ]:
        assert name in tool_names


def test_evidence_extraction_fields_envelope_is_normalized():
    payload = _normalize_evidence_extraction_payload(
        {
            "citation_id": 1,
            "evidence_basis": "abstract",
            "fields": {
                "intervention": "Intervention",
                "primary_outcome": "Primary outcome",
                "sample_size_intervention": 10,
                "sample_size_comparator": 12,
            },
        }
    )
    assert payload["intervention_or_exposure"] == "Intervention"
    assert payload["outcomes"] == "Primary outcome"
    assert payload["sample_size"] == "intervention=10; comparator=12"


def test_evidence_extraction_normalizes_chinese_evidence_basis():
    payload = _normalize_evidence_extraction_payload({"citation_id": 1, "evidence_basis": "PubMed全文摘要"})
    assert payload["evidence_basis"] == "abstract"


def test_mcp_saves_executable_strategy_and_rejects_raw_chinese_pico():
    project = create_review_project("Medication reconciliation", "Does pharmacist reconciliation reduce medication errors?")
    project_id = project["project"]["id"]
    saved = save_project_search_strategy(
        project_id,
        "pubmed",
        '("Medication Reconciliation"[Mesh] OR "medication reconciliation"[tiab]) AND pharmacist*[tiab]',
        "English PubMed strategy generated by search specialist.",
    )
    assert saved["search_strategy"]["version_number"] == 1
    with pytest.raises(ValueError, match="English/controlled vocabulary"):
        save_project_search_strategy(project_id, "pubmed", '"药师用药核对"[Title/Abstract]', "invalid")


def test_mcp_blocks_review_title_when_original_research_only():
    project = create_review_project("Original studies", "Does reconciliation reduce errors?", review_mode="quick_exploration")
    project_id = project["project"]["id"]
    citation = import_citations_to_project(project_id, "pubmed", [{"external_id": "123", "title": "Medication reconciliation: a systematic review"}])
    with pytest.raises(ValueError, match="Original-research-only"):
        submit_screening_decisions(project_id, [{"citation_id": citation["citations"][0]["id"], "decision": "include", "reason": "wrong", "actor": "test"}], original_research_only=True)


def test_client_online_allows_screening_but_blocks_export_until_included_preflight(monkeypatch):
    monkeypatch.setattr(settings, "literature_access_mode", "client_online")
    project = create_review_project("Preflight required", "Does reconciliation reduce errors?", review_mode="quick_exploration")
    project_id = project["project"]["id"]
    citation = import_citations_to_project(project_id, "pubmed", [{"external_id": "123", "title": "Eligible trial"}])
    submitted = submit_screening_decisions(project_id, [{
        "citation_id": citation["citations"][0]["id"],
        "decision": "include",
        "reason": "Matches the review question.",
        "actor": "test",
    }])
    assert submitted["project_status"] == "screening_completed"
    with Session(engine) as session:
        with pytest.raises(ValueError, match="explicit full-text preflight"):
            build_review_bundle_data(session, project_id)


def test_mcp_literature_access_status_reflects_offline_mode(monkeypatch):
    monkeypatch.setattr(settings, "literature_access_mode", "offline")

    status = get_literature_access_status()

    assert status["mode"] == "offline"
    assert status["live_database_requests_enabled"] is False


def test_mcp_import_citations_file_to_project(monkeypatch, tmp_path):
    import_dir = tmp_path / "literature-imports"
    import_dir.mkdir()
    (import_dir / "records.ris").write_text(
        "\n".join(
            [
                "TY  - JOUR",
                "TI  - Nurse-led follow-up after COPD discharge",
                "AU  - Li Q",
                "AU  - Zhao Y",
                "PY  - 2023",
                "DO  - 10.1000/copd-followup",
                "AB  - Follow-up intervention after discharge.",
                "ER  -",
            ]
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(settings, "literature_import_dir", str(import_dir))
    project = create_review_project("COPD follow-up review", "Does follow-up reduce readmission?")

    imported = import_citations_file_to_project(
        project["project"]["id"],
        "records.ris",
        source="offline_ris_export",
    )

    assert imported["parsed_count"] == 1
    assert imported["imported_count"] == 1
    assert imported["citations"][0]["title"] == "Nurse-led follow-up after COPD discharge"


def test_controlled_open_access_fetch_binds_full_text_to_local_citation(monkeypatch):
    monkeypatch.setattr(settings, "skill_receipt_key", None)
    project = create_review_project("Controlled source", "Does an intervention affect an outcome?", review_mode="quick_exploration")
    project_id = project["project"]["id"]
    citations = import_citations_to_project(
        project_id,
        "pubmed",
        [{
            "external_id": "12345",
            "title": "Verified source article",
            "doi": "10.1000/example",
            "abstract": "Randomized trial abstract.",
        }],
    )
    citation_id = citations["citations"][0]["id"]
    submit_screening_decisions(project_id, [{
        "citation_id": citation_id,
        "decision": "include",
        "reason": "Eligible test study.",
        "actor": "test",
    }])
    run_id = mcp._tool_manager._tools["start_evidence_extraction_workflow"].fn(project_id)["workflow"]["run_id"]

    async def fake_fetch(pmid: str):
        assert pmid == "12345"
        return {
            "pmid": "12345",
            "pmcid": "PMC123",
            "doi": "10.1000/example",
            "title": "Verified source article",
            "source_url": "https://www.ebi.ac.uk/europepmc/webservices/rest/PMC123/fullTextXML",
            "content_text": "Verified public XML full text with enough source-bound detail for the test.",
        }

    monkeypatch.setattr("app.mcp_server.fetch_europepmc_open_access_full_text", fake_fetch)
    result = asyncio.run(fetch_and_save_open_access_full_text(project_id, run_id, [citation_id]))
    assert result["saved_count"] == 1
    assert result["documents"][0]["citation_id"] == citation_id


def test_mcp_study_design_workflow_requires_external_approval(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "randomization_storage_dir", str(tmp_path))
    created = create_study_design_project(title="SGLT2 pragmatic RCT", research_question="Can an SGLT2 inhibitor reduce heart-failure hospitalization?", study_type="efficacy", study_design="RCT, parallel-group", population="Adults with type 2 diabetes and high cardiovascular risk", intervention="SGLT2 inhibitor", comparator="Standard care", outcome="Heart-failure hospitalization within 12 months", department="Cardiology", resource_summary="Estimated 300 eligible cases annually", data_attestation="deidentified_or_aggregate")
    project_id, run_id = created["project"]["id"], created["workflow"]["run_id"]
    blueprint = generate_study_design_blueprint(project_id, run_id)
    assert blueprint["reporting_standard"] == "SPIRIT/CONSORT"
    saved = save_study_design_content(project_id, run_id, inclusion_criteria="Adults with type 2 diabetes and documented cardiovascular risk.", exclusion_criteria="Pregnancy, contraindication, or unresolved safety concern.", primary_outcome="First heart-failure hospitalization within 12 months.", proposal_outline="Background; objectives; design; participants; outcomes; analysis; ethics.", secondary_outcomes="All-cause hospitalization and renal function change.", innovation_notes="Pragmatic implementation in routine cardiometabolic care.", feasibility_notes="The department estimates 300 potentially eligible cases per year.")
    assert saved["project"]["status"] == "content_drafted"
    sample_size = calculate_study_sample_size(project_id, run_id, method="proportions", group_one_value=0.18, group_two_value=0.12)
    assert sample_size["sample_size"]["total"] > 0
    plan = save_rct_randomization_plan(project_id, run_id, 24, ["standard_care", "sglt2"], 4)
    assert plan["randomization_plan"]["allocations_generated"] is False
    approval = request_study_design_approval(project_id, run_id)
    assert approval["approval"]["status"] == "pending"
    with pytest.raises(ValueError, match="Internal human confirmation"):
        generate_rct_randomization_schedule(project_id, run_id)
    with Session(engine) as session:
        approve_study_design_record(session, project_id, "authorized_researcher")
        assert len(get_study_design_workflow_events(session, project_id, run_id)) >= 6
    status = get_study_design_approval_status(project_id, run_id)
    assert status["approval"]["status"] == "approved"
    schedule = generate_rct_randomization_schedule(project_id, run_id)
    assert schedule["randomization_schedule"]["allocation_visible_to_agent"] is False
    exported = export_study_design_bundle(project_id, run_id)
    assert "Allocation sequence is withheld" in exported["markdown"]


def test_finalize_study_design_uses_one_internal_confirmation(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "randomization_storage_dir", str(tmp_path))
    created = create_study_design_project(
        title="One-step confirmation RCT",
        research_question="Can remote follow-up improve scheduled follow-up attendance?",
        study_type="efficacy",
        study_design="RCT, parallel-group",
        population="De-identified aggregate older adults with hypertension",
        intervention="Remote pharmacist education",
        comparator="Usual discharge guidance",
        outcome="Scheduled follow-up completed within 30 days",
        department="General Practice",
        resource_summary="Aggregate MVP test input",
        data_attestation="deidentified_or_aggregate",
    )
    project_id, run_id = created["project"]["id"], created["workflow"]["run_id"]
    generate_study_design_blueprint(project_id, run_id)
    save_study_design_content(
        project_id,
        run_id,
        inclusion_criteria="Adults aged 65 years or older with documented hypertension.",
        exclusion_criteria="Unable to complete follow-up or missing essential baseline information.",
        primary_outcome="Scheduled follow-up completed within 30 days.",
        proposal_outline="Background; objectives; design; participants; outcomes; analysis; ethics.",
        secondary_outcomes="Medication reconciliation completion.",
        innovation_notes="Structured remote transition support.",
        feasibility_notes="Aggregate recruitment capacity is sufficient for the demonstration assumptions.",
    )
    calculate_study_sample_size(project_id, run_id, method="proportions", group_one_value=0.55, group_two_value=0.70)
    save_rct_randomization_plan(project_id, run_id, 24, ["usual_care", "remote_followup"], 4)

    result = finalize_study_design(project_id, run_id, "current OpenCode operator")
    assert result["approval"]["status"] == "approved"
    assert result["randomization_schedule"]["allocation_visible_to_agent"] is False
    assert "Allocation sequence is withheld" in result["markdown"]


def test_chinese_randomized_controlled_design_supports_randomization_plan():
    created = create_study_design_project(
        title="中文随机对照试验",
        research_question="Does a transition-care intervention reduce readmission?",
        study_type="efficacy",
        study_design="前瞻性、随机、对照、开放标签的实效性临床试验",
        population="Adults discharged after heart-failure hospitalization",
        intervention="Transition-care intervention",
        comparator="Usual care",
        outcome="All-cause readmission within 30 days",
        department="Cardiology",
        resource_summary="Aggregate MVP test input",
        data_attestation="deidentified_or_aggregate",
    )
    project_id, run_id = created["project"]["id"], created["workflow"]["run_id"]
    plan = save_rct_randomization_plan(project_id, run_id, 24, ["intervention", "usual_care"], 4)
    assert plan["randomization_plan"]["allocations_generated"] is False


def test_mcp_project_workflow_closes_the_basic_loop():
    created = create_review_project(title="SGLT2 review", research_question="Do SGLT2 inhibitors reduce heart failure hospitalization?", pico_population="Adults with type 2 diabetes", pico_intervention="SGLT2 inhibitors", pico_comparator="Placebo or standard care", pico_outcome="Heart failure hospitalization", review_mode="quick_exploration")
    project_id = created["project"]["id"]
    strategy = generate_project_search_strategy(project_id)
    assert strategy["search_strategy"]["project_id"] == project_id
    imported = import_citations_to_project(project_id, "pubmed", [{"title": "Empagliflozin, Cardiovascular Outcomes, and Mortality in Type 2 Diabetes", "external_id": "26378978", "doi": "10.1056/NEJMoa1504720"}, {"title": "Empagliflozin duplicate", "external_id": "26378978-dup", "doi": "10.1056/NEJMoa1504720"}, {"title": "Dapagliflozin and Cardiovascular Outcomes in Type 2 Diabetes", "external_id": "30415602", "doi": "10.1056/NEJMoa1812389"}])
    assert imported["imported_count"] == 3
    assert deduplicate_project_citations(project_id)["removed_count"] == 1
    screening = submit_screening_decisions(project_id, [{"citation_id": imported["citations"][0]["id"], "decision": "include", "reason": "Directly matches the review question."}, {"citation_id": imported["citations"][2]["id"], "decision": "exclude", "reason": "Outcome reporting is not sufficiently aligned."}])
    assert screening["project_status"] == "screening_completed"


def test_search_pubmed_limits_abstract_context_for_agents(monkeypatch):
    async def fake_search_pubmed_records(query: str, limit: int):
        return [{"source": "pubmed", "external_id": "123", "title": "A relevant trial", "abstract": "A" * 4_000, "authors": "Author A", "publication_year": 2025, "doi": "10.1000/example"}]
    monkeypatch.setattr("app.mcp_server.search_pubmed_records", fake_search_pubmed_records)
    record = asyncio.run(search_pubmed("example query", limit=1))["records"][0]
    assert len(record["abstract"]) <= 1_200
    assert record["abstract"].endswith("...")
