#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
SOURCE_ROOT="$ROOT_DIR/vendor/medical-research-skills/scientific-skills"
TARGET_ROOT="$ROOT_DIR/.agents/skills"

if [ ! -d "$SOURCE_ROOT" ]; then
  echo "Upstream skill library not found at: $SOURCE_ROOT" >&2
  echo "Clone the repository into vendor/medical-research-skills first." >&2
  exit 1
fi

mkdir -p "$TARGET_ROOT"

SKILL_PATHS=(
  "Evidence Insight/pubmed-search-specialist"
  "Evidence Insight/pubmed-database"
  "Evidence Insight/reference-search"
  "Evidence Insight/literature-filtering"
  "Evidence Insight/systematic-review-screener"
  "Evidence Insight/clinical-study-info-extractor"
  "Evidence Insight/methodology-extractor"
  "Evidence Insight/citation-chasing-mapping"
  "Evidence Insight/retraction-watcher"
  "Data Analysis/baseline-extraction-for-clinical-trials"
  "Data Analysis/outcome-extraction-for-clinical-trials"
  "Data Analysis/meta-screening-fulltext"
  "Data Analysis/meta-analysis"
  "Data Analysis/meta-forest-binary-plot"
  "Data Analysis/rct-bias-assessment-rob2"
  "Data Analysis/cohort-study-quality-assessment-nos"
  "Data Analysis/diagnostic-study-quality-assessment-quadas-2"
  "Academic Writing/literature-review"
  "Academic Writing/systematic-review"
  "Academic Writing/biomed-outline-generator"
  "Academic Writing/method-writing"
  "Academic Writing/discussion-section-architect"
  "Protocol Design/clinic-research-design"
  "Protocol Design/inclusion-criteria-gen"
  "Protocol Design/sample-size-basic"
  "Protocol Design/randomization-gen"
  "Protocol Design/research-proposal-generator"
  "Other/phi-prompt-guard"
  "Other/fulltext-fetcher"
  "Other/pdf-extract"
)

copied=0

for relative_path in "${SKILL_PATHS[@]}"; do
  source_dir="$SOURCE_ROOT/$relative_path"
  skill_name="$(basename "$relative_path")"
  target_dir="$TARGET_ROOT/$skill_name"
  cache_dir=""

  if [ ! -d "$source_dir" ]; then
    echo "Missing upstream skill directory: $source_dir" >&2
    exit 1
  fi

  # A few historical skill packages accidentally tracked Python bytecode. Preserve it so
  # running this synchronization command does not create unrelated binary deletions.
  if [ -d "$target_dir/scripts/__pycache__" ]; then
    cache_dir="$(mktemp -d)"
    cp -R "$target_dir/scripts/__pycache__" "$cache_dir/__pycache__"
  fi
  rm -rf "$target_dir"
  cp -R "$source_dir" "$target_dir"
  if [ -n "$cache_dir" ]; then
    mkdir -p "$target_dir/scripts"
    cp -R "$cache_dir/__pycache__" "$target_dir/scripts/__pycache__"
    rm -rf "$cache_dir"
  fi
  copied=$((copied + 1))
  echo "Synced skill: $skill_name"
done

cat >"$TARGET_ROOT/SELECTED_SKILLS.md" <<'EOF'
# Selected Skills For Medical Research Agents

This file is generated by `scripts/opencode/sync-medical-research-skills.sh`.

The current OpenCode integrations sync these upstream skills:

- pubmed-search-specialist
- pubmed-database
- reference-search
- literature-filtering
- systematic-review-screener
- clinical-study-info-extractor
- methodology-extractor
- citation-chasing-mapping
- retraction-watcher
- fulltext-fetcher
- pdf-extract
- baseline-extraction-for-clinical-trials
- outcome-extraction-for-clinical-trials
- meta-screening-fulltext
- meta-analysis
- meta-forest-binary-plot
- rct-bias-assessment-rob
- cohort-study-quality-assessment-nos
- diagnostic-study-quality-assessment-quadas
- literature-review
- systematic-review
- biomed-outline-generator
- method-writing
- discussion-section-architect
- clinic-research-design
- inclusion-criteria-gen
- sample-size-basic
- randomization-gen
- research-proposal-generator
- phi-prompt-guard
EOF

echo "Done. Synced $copied skills into $TARGET_ROOT"
